# Generated by Django 2.2.4 on 2019-09-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0005_auto_20190905_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
